version: '3.7'

services:
  varada:
    image: varada/varada:364.14.14-varada
    privileged: true
    volumes:
      - /usr/lib/presto/:/usr/lib/presto
      - /var/log/presto/:/var/log/presto
      - /usr/lib/varada/:/usr/lib/varada
      - /opt/varada/config/:/opt/varada/config
      - /etc/presto/:/etc/presto/
      - /etc/varada/:/etc/varada/
      - /var/lib/presto/:/var/lib/presto
    environment:
      - IS_BACKEND=true
      - IS_COORDINATOR=true
      - IS_STANDALONE=false
      - POST_INSTALL_PARAMS=
      - POST_INSTALL_SCRIPT=null
    expose:
      - 8080
      - 8088
      - 8089
    ports:
      - 8080:8080
      - 8089:8089
      - 8088:8088
    ulimits:
      nofile:
        soft: 8192
        hard: 8192
      core: 0
    container_name: varada
  accelerator:
    image: varada/accelerator:0.2.13
    ports:
      - 8000:8000
    restart: on-failure:10
    container_name: accelerator
  deployer:
    image: varada/deployer:0.2.13
    ports:
      - 8001:8001
    restart: on-failure:10
    container_name: deployer
  clustermanager:
    image: varada/clustermanager:0.2.13
    volumes:
      - /opt/varada/config/:/opt/varada/config
    ports:
      - 8888:8888
    environment:
      - EXTRA_PARAMS=-Ddw.server.applicationConnectors[0].port=8888 -Ddw.presto.coordinatorHost=varada
    restart: on-failure:10
    container_name: clustermanager
